config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :aaas
  post '/get_log', to: 'aaas#get_log'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aaa.rb
# == Schema Information
#
# Table name: aaas
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  test_id    :string
#

class Aaa < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  order_no   :string
#  channel    :string
#  body       :string
#  subject    :string
#  amount     :integer
#  metadata   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ApplicationRecord
end

app/controllers/aaas_controller.rb
class AaasController < ApplicationController
  before_action :set_aaa, only: [:show, :edit, :update, :destroy]

  # GET /aaas
  # GET /aaas.json
  def index
    @aaas = Aaa.all
  end

  # GET /aaas/1
  # GET /aaas/1.json
  def show
  end

  # GET /aaas/new
  def new
    @aaa = Aaa.new
    a = Pingpp::Charge.create(
                          :order_no  => "12345678911",
                          :app       => { :id => APP_ID },
                          :channel   => 'wx',
                          :amount    => 100,
                          :client_ip => "127.0.0.1",
                          :currency  => "cny",
                          :subject   => "Your Subject",
                          :body      => "Your Body"
                        )
    @aaa.test_id = a["id"]
    @aaa.save
    puts aa unless @aaa.save


  end

  def get_log
    @aaa = Aaa.new
    @aaa.test_id = params[:id]
    @aaa.save
  end


  # GET /aaas/1/edit
  def edit
  end

  # POST /aaas
  # POST /aaas.json
  def create
    @aaa = Aaa.new(aaa_params)

    respond_to do |format|
      if @aaa.save
        format.html { redirect_to @aaa, notice: 'Aaa was successfully created.' }
        format.json { render :show, status: :created, location: @aaa }
      else
        format.html { render :new }
        format.json { render json: @aaa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aaas/1
  # PATCH/PUT /aaas/1.json
  def update
    respond_to do |format|
      if @aaa.update(aaa_params)
        format.html { redirect_to @aaa, notice: 'Aaa was successfully updated.' }
        format.json { render :show, status: :ok, location: @aaa }
      else
        format.html { render :edit }
        format.json { render json: @aaa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aaas/1
  # DELETE /aaas/1.json
  def destroy
    @aaa.destroy
    respond_to do |format|
      format.html { redirect_to aaas_url, notice: 'Aaa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aaa
      @aaa = Aaa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aaa_params
      params.fetch(:aaa, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_no)
    end
end

app/helpers/aaas_helper.rb
module AaasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/aaas/_form.html.erb
<%= form_for(aaa) do |f| %>
  <% if aaa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aaa.errors.count, "error") %> prohibited this aaa from being saved:</h2>

      <ul>
      <% aaa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aaas/edit.html.erb
<h1>Editing Aaa</h1>

<%= render 'form', aaa: @aaa %>

<%= link_to 'Show', @aaa %> |
<%= link_to 'Back', aaas_path %>

app/views/aaas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aaas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aaas.each do |aaa| %>
      <tr>
        <td><%= aaa.test_id %></td>
        <!-- <td><%= link_to "asd", "/get_log", method: :post %></td> -->
        <td><%= link_to 'Show', aaa %></td>
        <td><%= link_to 'Edit', edit_aaa_path(aaa) %></td>
        <td><%= link_to 'Destroy', aaa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aaa', new_aaa_path %>

app/views/aaas/new.html.erb
<h1>New Aaa</h1>

<%= render 'form', aaa: @aaa %>

<%= link_to 'Back', aaas_path %>

app/views/aaas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_aaa_path(@aaa) %> |
<%= link_to 'Back', aaas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pingpp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_no %>
    <%= f.text_field :order_no %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_no %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order no:</strong>
  <%= @order.order_no %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>